# Generated by Django 5.0.2 on 2024-02-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ContalNum',
            new_name='ContactNum',
        ),
    ]
