# Generated by Django 5.0.2 on 2024-02-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_contalnum_patient_contactnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ContactNum',
            new_name='contactNum',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Role',
            new_name='role',
        ),
    ]
